// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkyOgtFvybjRPc1zhAy1AE-PfWAgfShYg',
    appId: '1:267387384317:web:aaa824c5ca28d9c37b2994',
    messagingSenderId: '267387384317',
    projectId: 'trikesystem',
    authDomain: 'trikesystem.firebaseapp.com',
    storageBucket: 'trikesystem.firebasestorage.app',
    measurementId: 'G-M9HVDDQLK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0v1T9Lv7MoQnV7wohVQGFZdaMPNwKNok',
    appId: '1:267387384317:android:df4933a3cbdb17797b2994',
    messagingSenderId: '267387384317',
    projectId: 'trikesystem',
    storageBucket: 'trikesystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsQlzsgOsAOu-r9lQwOyHjgPhHms1o7K8',
    appId: '1:267387384317:ios:593efced09c26e787b2994',
    messagingSenderId: '267387384317',
    projectId: 'trikesystem',
    storageBucket: 'trikesystem.firebasestorage.app',
    iosBundleId: 'com.example.tricyclesystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsQlzsgOsAOu-r9lQwOyHjgPhHms1o7K8',
    appId: '1:267387384317:ios:593efced09c26e787b2994',
    messagingSenderId: '267387384317',
    projectId: 'trikesystem',
    storageBucket: 'trikesystem.firebasestorage.app',
    iosBundleId: 'com.example.tricyclesystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkyOgtFvybjRPc1zhAy1AE-PfWAgfShYg',
    appId: '1:267387384317:web:5af201f0301c04e37b2994',
    messagingSenderId: '267387384317',
    projectId: 'trikesystem',
    authDomain: 'trikesystem.firebaseapp.com',
    storageBucket: 'trikesystem.firebasestorage.app',
    measurementId: 'G-WB1BKCXNKX',
  );
}
